/*
* generated by Xtext
*/
package dk.itu.smdp.survey.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import dk.itu.smdp.survey.xtext.services.TacoGrammarAccess;

public class TacoParser extends AbstractContentAssistParser {
	
	@Inject
	private TacoGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser createParser() {
		dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser result = new dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getQuestionAccess().getAlternatives(), "rule__Question__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getSurveyAccess().getGroup_2(), "rule__Survey__Group_2__0");
					put(grammarAccess.getSurveyAccess().getGroup_3(), "rule__Survey__Group_3__0");
					put(grammarAccess.getCategoryAccess().getGroup(), "rule__Category__Group__0");
					put(grammarAccess.getCategoryAccess().getGroup_2(), "rule__Category__Group_2__0");
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getPersonAccess().getGroup_2(), "rule__Person__Group_2__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getAnswerAccess().getGroup(), "rule__Answer__Group__0");
					put(grammarAccess.getAnswerAccess().getGroup_3(), "rule__Answer__Group_3__0");
					put(grammarAccess.getAnswerAccess().getGroup_4(), "rule__Answer__Group_4__0");
					put(grammarAccess.getMultipleChoice_ImplAccess().getGroup(), "rule__MultipleChoice_Impl__Group__0");
					put(grammarAccess.getRankingAccess().getGroup(), "rule__Ranking__Group__0");
					put(grammarAccess.getRatingAccess().getGroup(), "rule__Rating__Group__0");
					put(grammarAccess.getYesNoAccess().getGroup(), "rule__YesNo__Group__0");
					put(grammarAccess.getOpenFieldAccess().getGroup(), "rule__OpenField__Group__0");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getGroup(), "rule__MutuallyExclusive_Impl__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getSurveyAccess().getTitleAssignment_1(), "rule__Survey__TitleAssignment_1");
					put(grammarAccess.getSurveyAccess().getDateAssignment_2_1(), "rule__Survey__DateAssignment_2_1");
					put(grammarAccess.getSurveyAccess().getDescriptionAssignment_3_1(), "rule__Survey__DescriptionAssignment_3_1");
					put(grammarAccess.getSurveyAccess().getPersonAssignment_4(), "rule__Survey__PersonAssignment_4");
					put(grammarAccess.getSurveyAccess().getCategoriesAssignment_5(), "rule__Survey__CategoriesAssignment_5");
					put(grammarAccess.getSurveyAccess().getCategoriesAssignment_6(), "rule__Survey__CategoriesAssignment_6");
					put(grammarAccess.getCategoryAccess().getTitleAssignment_1(), "rule__Category__TitleAssignment_1");
					put(grammarAccess.getCategoryAccess().getDescriptionAssignment_2_1(), "rule__Category__DescriptionAssignment_2_1");
					put(grammarAccess.getCategoryAccess().getPagesAssignment_3(), "rule__Category__PagesAssignment_3");
					put(grammarAccess.getCategoryAccess().getPagesAssignment_4(), "rule__Category__PagesAssignment_4");
					put(grammarAccess.getPersonAccess().getAttributeAssignment_1(), "rule__Person__AttributeAssignment_1");
					put(grammarAccess.getPersonAccess().getAttributeAssignment_2_1(), "rule__Person__AttributeAssignment_2_1");
					put(grammarAccess.getPageAccess().getQuestionsAssignment_1(), "rule__Page__QuestionsAssignment_1");
					put(grammarAccess.getPageAccess().getQuestionsAssignment_2(), "rule__Page__QuestionsAssignment_2");
					put(grammarAccess.getAnswerAccess().getDescriptionAssignment_2(), "rule__Answer__DescriptionAssignment_2");
					put(grammarAccess.getAnswerAccess().getIsUserInputAllowedAssignment_3_0(), "rule__Answer__IsUserInputAllowedAssignment_3_0");
					put(grammarAccess.getAnswerAccess().getSubquestionAssignment_4_1(), "rule__Answer__SubquestionAssignment_4_1");
					put(grammarAccess.getAnswerAccess().getSubquestionAssignment_4_2(), "rule__Answer__SubquestionAssignment_4_2");
					put(grammarAccess.getMultipleChoice_ImplAccess().getIsMandatoryAssignment_1(), "rule__MultipleChoice_Impl__IsMandatoryAssignment_1");
					put(grammarAccess.getMultipleChoice_ImplAccess().getQuestionTextAssignment_2(), "rule__MultipleChoice_Impl__QuestionTextAssignment_2");
					put(grammarAccess.getMultipleChoice_ImplAccess().getMinAssignment_4(), "rule__MultipleChoice_Impl__MinAssignment_4");
					put(grammarAccess.getMultipleChoice_ImplAccess().getMaxAssignment_6(), "rule__MultipleChoice_Impl__MaxAssignment_6");
					put(grammarAccess.getMultipleChoice_ImplAccess().getAnswersAssignment_8(), "rule__MultipleChoice_Impl__AnswersAssignment_8");
					put(grammarAccess.getMultipleChoice_ImplAccess().getAnswersAssignment_9(), "rule__MultipleChoice_Impl__AnswersAssignment_9");
					put(grammarAccess.getRankingAccess().getIsMandatoryAssignment_1(), "rule__Ranking__IsMandatoryAssignment_1");
					put(grammarAccess.getRankingAccess().getQuestionTextAssignment_2(), "rule__Ranking__QuestionTextAssignment_2");
					put(grammarAccess.getRankingAccess().getAnswersAssignment_6(), "rule__Ranking__AnswersAssignment_6");
					put(grammarAccess.getRankingAccess().getAnswersAssignment_7(), "rule__Ranking__AnswersAssignment_7");
					put(grammarAccess.getRatingAccess().getIsMandatoryAssignment_1(), "rule__Rating__IsMandatoryAssignment_1");
					put(grammarAccess.getRatingAccess().getQuestionTextAssignment_2(), "rule__Rating__QuestionTextAssignment_2");
					put(grammarAccess.getRatingAccess().getStartAssignment_4(), "rule__Rating__StartAssignment_4");
					put(grammarAccess.getRatingAccess().getEndAssignment_6(), "rule__Rating__EndAssignment_6");
					put(grammarAccess.getRatingAccess().getIntervalAssignment_8(), "rule__Rating__IntervalAssignment_8");
					put(grammarAccess.getYesNoAccess().getIsMandatoryAssignment_1(), "rule__YesNo__IsMandatoryAssignment_1");
					put(grammarAccess.getYesNoAccess().getQuestionTextAssignment_2(), "rule__YesNo__QuestionTextAssignment_2");
					put(grammarAccess.getOpenFieldAccess().getIsMandatoryAssignment_1(), "rule__OpenField__IsMandatoryAssignment_1");
					put(grammarAccess.getOpenFieldAccess().getQuestionTextAssignment_2(), "rule__OpenField__QuestionTextAssignment_2");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getIsMandatoryAssignment_1(), "rule__MutuallyExclusive_Impl__IsMandatoryAssignment_1");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getQuestionTextAssignment_2(), "rule__MutuallyExclusive_Impl__QuestionTextAssignment_2");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getAnswersAssignment_3(), "rule__MutuallyExclusive_Impl__AnswersAssignment_3");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getAnswersAssignment_4(), "rule__MutuallyExclusive_Impl__AnswersAssignment_4");
					put(grammarAccess.getPersonAttributeAccess().getKeyAssignment(), "rule__PersonAttribute__KeyAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser typedParser = (dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser) parser;
			typedParser.entryRuleSurvey();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TacoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TacoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
