/*
* generated by Xtext
*/
package dk.itu.smdp.survey.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import dk.itu.smdp.survey.xtext.services.TacoGrammarAccess;

public class TacoParser extends AbstractContentAssistParser {
	
	@Inject
	private TacoGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser createParser() {
		dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser result = new dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getQuestionAccess().getAlternatives(), "rule__Question__Alternatives");
					put(grammarAccess.getDescriptionAccess().getAlternatives(), "rule__Description__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getSurveyAccess().getGroup_3(), "rule__Survey__Group_3__0");
					put(grammarAccess.getSurveyAccess().getGroup_4(), "rule__Survey__Group_4__0");
					put(grammarAccess.getCategoryAccess().getGroup(), "rule__Category__Group__0");
					put(grammarAccess.getCategoryAccess().getGroup_5(), "rule__Category__Group_5__0");
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getPersonAccess().getGroup_3(), "rule__Person__Group_3__0");
					put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
					put(grammarAccess.getOptionAccess().getGroup(), "rule__Option__Group__0");
					put(grammarAccess.getOptionAccess().getGroup_3(), "rule__Option__Group_3__0");
					put(grammarAccess.getOptionAccess().getGroup_4(), "rule__Option__Group_4__0");
					put(grammarAccess.getOptionAccess().getGroup_5(), "rule__Option__Group_5__0");
					put(grammarAccess.getOptionAccess().getGroup_5_1(), "rule__Option__Group_5_1__0");
					put(grammarAccess.getMultipleChoice_ImplAccess().getGroup(), "rule__MultipleChoice_Impl__Group__0");
					put(grammarAccess.getMultipleChoice_ImplAccess().getGroup_5(), "rule__MultipleChoice_Impl__Group_5__0");
					put(grammarAccess.getMultipleChoice_ImplAccess().getGroup_12(), "rule__MultipleChoice_Impl__Group_12__0");
					put(grammarAccess.getMultipleChoice_ImplAccess().getGroup_13(), "rule__MultipleChoice_Impl__Group_13__0");
					put(grammarAccess.getRankingAccess().getGroup(), "rule__Ranking__Group__0");
					put(grammarAccess.getRankingAccess().getGroup_5(), "rule__Ranking__Group_5__0");
					put(grammarAccess.getRankingAccess().getGroup_6(), "rule__Ranking__Group_6__0");
					put(grammarAccess.getRankingAccess().getGroup_7(), "rule__Ranking__Group_7__0");
					put(grammarAccess.getRatingAccess().getGroup(), "rule__Rating__Group__0");
					put(grammarAccess.getRatingAccess().getGroup_5(), "rule__Rating__Group_5__0");
					put(grammarAccess.getRatingAccess().getGroup_12(), "rule__Rating__Group_12__0");
					put(grammarAccess.getRatingAccess().getGroup_13(), "rule__Rating__Group_13__0");
					put(grammarAccess.getRatingAccess().getGroup_14(), "rule__Rating__Group_14__0");
					put(grammarAccess.getYesNoAccess().getGroup(), "rule__YesNo__Group__0");
					put(grammarAccess.getYesNoAccess().getGroup_5(), "rule__YesNo__Group_5__0");
					put(grammarAccess.getYesNoAccess().getGroup_6(), "rule__YesNo__Group_6__0");
					put(grammarAccess.getYesNoAccess().getGroup_7(), "rule__YesNo__Group_7__0");
					put(grammarAccess.getOpenFieldAccess().getGroup(), "rule__OpenField__Group__0");
					put(grammarAccess.getOpenFieldAccess().getGroup_5(), "rule__OpenField__Group_5__0");
					put(grammarAccess.getOpenFieldAccess().getGroup_6(), "rule__OpenField__Group_6__0");
					put(grammarAccess.getOpenFieldAccess().getGroup_7(), "rule__OpenField__Group_7__0");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getGroup(), "rule__MutuallyExclusive_Impl__Group__0");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getGroup_5(), "rule__MutuallyExclusive_Impl__Group_5__0");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getGroup_6(), "rule__MutuallyExclusive_Impl__Group_6__0");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getGroup_7(), "rule__MutuallyExclusive_Impl__Group_7__0");
					put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
					put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
					put(grammarAccess.getSurveyAccess().getTitleAssignment_2(), "rule__Survey__TitleAssignment_2");
					put(grammarAccess.getSurveyAccess().getDateAssignment_3_2(), "rule__Survey__DateAssignment_3_2");
					put(grammarAccess.getSurveyAccess().getDescriptionAssignment_4_2(), "rule__Survey__DescriptionAssignment_4_2");
					put(grammarAccess.getSurveyAccess().getPersonAssignment_5(), "rule__Survey__PersonAssignment_5");
					put(grammarAccess.getSurveyAccess().getCategoriesAssignment_6(), "rule__Survey__CategoriesAssignment_6");
					put(grammarAccess.getSurveyAccess().getCategoriesAssignment_7(), "rule__Survey__CategoriesAssignment_7");
					put(grammarAccess.getCategoryAccess().getTitleAssignment_4(), "rule__Category__TitleAssignment_4");
					put(grammarAccess.getCategoryAccess().getDescriptionAssignment_5_2(), "rule__Category__DescriptionAssignment_5_2");
					put(grammarAccess.getCategoryAccess().getStepsAssignment_6(), "rule__Category__StepsAssignment_6");
					put(grammarAccess.getCategoryAccess().getStepsAssignment_7(), "rule__Category__StepsAssignment_7");
					put(grammarAccess.getPersonAccess().getAttributeAssignment_2(), "rule__Person__AttributeAssignment_2");
					put(grammarAccess.getPersonAccess().getAttributeAssignment_3_1(), "rule__Person__AttributeAssignment_3_1");
					put(grammarAccess.getStepAccess().getQuestionsAssignment_2(), "rule__Step__QuestionsAssignment_2");
					put(grammarAccess.getStepAccess().getQuestionsAssignment_3(), "rule__Step__QuestionsAssignment_3");
					put(grammarAccess.getOptionAccess().getIsCheckedByDefaultAssignment_3_2(), "rule__Option__IsCheckedByDefaultAssignment_3_2");
					put(grammarAccess.getOptionAccess().getIsUserInputAllowedAssignment_4_2(), "rule__Option__IsUserInputAllowedAssignment_4_2");
					put(grammarAccess.getOptionAccess().getContainsAssignment_5_0(), "rule__Option__ContainsAssignment_5_0");
					put(grammarAccess.getOptionAccess().getContainsAssignment_5_1_1(), "rule__Option__ContainsAssignment_5_1_1");
					put(grammarAccess.getMultipleChoice_ImplAccess().getQuestionTextAssignment_4(), "rule__MultipleChoice_Impl__QuestionTextAssignment_4");
					put(grammarAccess.getMultipleChoice_ImplAccess().getIsMandatoryAssignment_5_2(), "rule__MultipleChoice_Impl__IsMandatoryAssignment_5_2");
					put(grammarAccess.getMultipleChoice_ImplAccess().getMinAssignment_8(), "rule__MultipleChoice_Impl__MinAssignment_8");
					put(grammarAccess.getMultipleChoice_ImplAccess().getMaxAssignment_11(), "rule__MultipleChoice_Impl__MaxAssignment_11");
					put(grammarAccess.getMultipleChoice_ImplAccess().getOptionAssignment_12_0(), "rule__MultipleChoice_Impl__OptionAssignment_12_0");
					put(grammarAccess.getMultipleChoice_ImplAccess().getOptionAssignment_12_1(), "rule__MultipleChoice_Impl__OptionAssignment_12_1");
					put(grammarAccess.getMultipleChoice_ImplAccess().getSubquestionAssignment_13_2(), "rule__MultipleChoice_Impl__SubquestionAssignment_13_2");
					put(grammarAccess.getMultipleChoice_ImplAccess().getSubquestionAssignment_13_3(), "rule__MultipleChoice_Impl__SubquestionAssignment_13_3");
					put(grammarAccess.getRankingAccess().getQuestionTextAssignment_4(), "rule__Ranking__QuestionTextAssignment_4");
					put(grammarAccess.getRankingAccess().getIsMandatoryAssignment_5_2(), "rule__Ranking__IsMandatoryAssignment_5_2");
					put(grammarAccess.getRankingAccess().getOptionAssignment_6_0(), "rule__Ranking__OptionAssignment_6_0");
					put(grammarAccess.getRankingAccess().getOptionAssignment_6_1(), "rule__Ranking__OptionAssignment_6_1");
					put(grammarAccess.getRankingAccess().getSubquestionAssignment_7_2(), "rule__Ranking__SubquestionAssignment_7_2");
					put(grammarAccess.getRankingAccess().getSubquestionAssignment_7_3(), "rule__Ranking__SubquestionAssignment_7_3");
					put(grammarAccess.getRatingAccess().getQuestionTextAssignment_4(), "rule__Rating__QuestionTextAssignment_4");
					put(grammarAccess.getRatingAccess().getIsMandatoryAssignment_5_2(), "rule__Rating__IsMandatoryAssignment_5_2");
					put(grammarAccess.getRatingAccess().getStartAssignment_8(), "rule__Rating__StartAssignment_8");
					put(grammarAccess.getRatingAccess().getEndAssignment_11(), "rule__Rating__EndAssignment_11");
					put(grammarAccess.getRatingAccess().getIntervalAssignment_12_2(), "rule__Rating__IntervalAssignment_12_2");
					put(grammarAccess.getRatingAccess().getOptionAssignment_13_0(), "rule__Rating__OptionAssignment_13_0");
					put(grammarAccess.getRatingAccess().getOptionAssignment_13_1(), "rule__Rating__OptionAssignment_13_1");
					put(grammarAccess.getRatingAccess().getSubquestionAssignment_14_2(), "rule__Rating__SubquestionAssignment_14_2");
					put(grammarAccess.getRatingAccess().getSubquestionAssignment_14_3(), "rule__Rating__SubquestionAssignment_14_3");
					put(grammarAccess.getYesNoAccess().getQuestionTextAssignment_4(), "rule__YesNo__QuestionTextAssignment_4");
					put(grammarAccess.getYesNoAccess().getIsMandatoryAssignment_5_2(), "rule__YesNo__IsMandatoryAssignment_5_2");
					put(grammarAccess.getYesNoAccess().getOptionAssignment_6_0(), "rule__YesNo__OptionAssignment_6_0");
					put(grammarAccess.getYesNoAccess().getOptionAssignment_6_1(), "rule__YesNo__OptionAssignment_6_1");
					put(grammarAccess.getYesNoAccess().getSubquestionAssignment_7_2(), "rule__YesNo__SubquestionAssignment_7_2");
					put(grammarAccess.getYesNoAccess().getSubquestionAssignment_7_3(), "rule__YesNo__SubquestionAssignment_7_3");
					put(grammarAccess.getOpenFieldAccess().getQuestionTextAssignment_4(), "rule__OpenField__QuestionTextAssignment_4");
					put(grammarAccess.getOpenFieldAccess().getIsMandatoryAssignment_5_2(), "rule__OpenField__IsMandatoryAssignment_5_2");
					put(grammarAccess.getOpenFieldAccess().getOptionAssignment_6_0(), "rule__OpenField__OptionAssignment_6_0");
					put(grammarAccess.getOpenFieldAccess().getOptionAssignment_6_1(), "rule__OpenField__OptionAssignment_6_1");
					put(grammarAccess.getOpenFieldAccess().getSubquestionAssignment_7_2(), "rule__OpenField__SubquestionAssignment_7_2");
					put(grammarAccess.getOpenFieldAccess().getSubquestionAssignment_7_3(), "rule__OpenField__SubquestionAssignment_7_3");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getQuestionTextAssignment_4(), "rule__MutuallyExclusive_Impl__QuestionTextAssignment_4");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getIsMandatoryAssignment_5_2(), "rule__MutuallyExclusive_Impl__IsMandatoryAssignment_5_2");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getOptionAssignment_6_0(), "rule__MutuallyExclusive_Impl__OptionAssignment_6_0");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getOptionAssignment_6_1(), "rule__MutuallyExclusive_Impl__OptionAssignment_6_1");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getSubquestionAssignment_7_2(), "rule__MutuallyExclusive_Impl__SubquestionAssignment_7_2");
					put(grammarAccess.getMutuallyExclusive_ImplAccess().getSubquestionAssignment_7_3(), "rule__MutuallyExclusive_Impl__SubquestionAssignment_7_3");
					put(grammarAccess.getTextAccess().getContentAssignment_2(), "rule__Text__ContentAssignment_2");
					put(grammarAccess.getImageAccess().getContentAssignment_2(), "rule__Image__ContentAssignment_2");
					put(grammarAccess.getPersonAttributeAccess().getKeyAssignment(), "rule__PersonAttribute__KeyAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser typedParser = (dk.itu.smdp.survey.xtext.ui.contentassist.antlr.internal.InternalTacoParser) parser;
			typedParser.entryRuleSurvey();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TacoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TacoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
