/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class TacoQuickfixProvider extends DefaultQuickfixProvider {
}
