/*
* generated by Xtext
*/
package dk.itu.smdp.survey.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TacoUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.itu.smdp.survey.xtext.ui.internal.TacoActivator.getInstance().getInjector("dk.itu.smdp.survey.xtext.Taco");
	}
	
}
