/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.serializer;

import dk.itu.smdp.survey.xtext.serializer.AbstractTacoSyntacticSequencer;

@SuppressWarnings("all")
public class TacoSyntacticSequencer extends AbstractTacoSyntacticSequencer {
}
