/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.serializer;

import dk.itu.smdp.survey.xtext.serializer.AbstractTacoSemanticSequencer;

@SuppressWarnings("all")
public class TacoSemanticSequencer extends AbstractTacoSemanticSequencer {
}
