/*
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TacoUiModule extends dk.itu.smdp.survey.xtext.ui.AbstractTacoUiModule {
	public TacoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
