/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.ui.contentassist;

import dk.itu.smdp.survey.xtext.ui.contentassist.AbstractTacoProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TacoProposalProvider extends AbstractTacoProposalProvider {
}
