/**
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.validation;

import dk.itu.smdp.survey.xtext.validation.AbstractTacoValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TacoValidator extends AbstractTacoValidator {
}
