/*
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.validation

import SurveyModel.MultipleChoice
import SurveyModel.Rating
import SurveyModel.SurveyModelPackage
import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class TacoValidator extends AbstractTacoValidator {
	
	public static final String CHECK_MULTIPLE_CHOICE_MAX_MIN = "check_multiple_choice_max_min";
	public static final String CHECK_RATING_START_END = "check_rating_start_end";
	public static final String CHECK_RATING_INTERVAL = "check_rating_interval";
	
	@Check
	def checkMultipleChoiceMaxMin(MultipleChoice it)
	{
		if(max < min)
		{
			error("The max value must be higher than or equal to the min value : [min-max]",
				SurveyModelPackage.Literals.MULTIPLE_CHOICE__MAX,
				CHECK_MULTIPLE_CHOICE_MAX_MIN,
				Integer.toString(max)
			);
		}
	}
	
	@Check
	def checkRatingStartEnd(Rating it)
	{
		if(end <= start)
		{
			error("The end value must be higher than the start value : [start-end, interval]",
				SurveyModelPackage.Literals.RATING__END,
				CHECK_RATING_START_END,
				Integer.toString(end)
			);
		}
	}
	
	@Check
	def checkRatingInterval(Rating it)
	{
		if((end - start) < interval)
		{
			error("The interval value must be smaller than the distance between start and end : [start-end, interval]",
				SurveyModelPackage.Literals.RATING__INTERVAL,
				CHECK_RATING_INTERVAL,
				Integer.toString(interval)
			);
		}
	}
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
