/*
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TacoRuntimeModule extends dk.itu.smdp.survey.xtext.AbstractTacoRuntimeModule {

}
