/*
* generated by Xtext
*/
package dk.itu.smdp.survey.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TacoStandaloneSetup extends TacoStandaloneSetupGenerated{

	public static void doSetup() {
		new TacoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

