/*
 * generated by Xtext
 */
package dk.itu.smdp.survey.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.smdp.survey.xtext.ui.internal.TacoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TacoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TacoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TacoActivator.getInstance().getInjector(TacoActivator.DK_ITU_SMDP_SURVEY_XTEXT_TACO);
	}
	
}
